ClassBooksWebApp/Controllers/ClassBookController.cs
using ClassBooksWebApp.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Configuration;
using System.Web.Mvc;

namespace ClassBooksWebApp.Controllers
{
    public class ClassBookController : Controller
    {
        readonly HttpClient _apiClient = new HttpClient();
        private readonly string _serviceUrl = WebConfigurationManager.AppSettings["apiUrl"];

        // GET: ClassBook
        public ActionResult Index()
        {
            if (Session["UserId"] == null) return View("~/Views/Login/Login.cshtml");
            return View();
        }

        //get all catalogues of students owned by teacher
        [HttpGet]
        public async Task<JsonResult> GetClassBooks()
        {
            var response = await _apiClient.GetAsync(new Uri(string.Format(_serviceUrl + "{0}/{1}", "/api/classBooks", Session["UserId"].ToString())));

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var items = JsonConvert.DeserializeObject<List<ClassBook>>(content);
                return Json(items, JsonRequestBehavior.AllowGet);
            }

            return null;
        }

        public async Task<HttpResponseMessage> CreateClassBook(ClassBook classBook)
        {
            classBook.TeacherId = Session["UserId"].ToString();

            var content = new StringContent(JsonConvert.SerializeObject(classBook), Encoding.UTF8, "application/json");
            var result = await _apiClient.PostAsync(new Uri(string.Format(_serviceUrl + "{0}", "/api/classBooks/create")), content);
            return result;
        }

        public async Task<JsonResult> AddStudentToClassBook(ClassBookBindingModel id)
        {
            var content = new StringContent(JsonConvert.SerializeObject(id), Encoding.UTF8, "application/json");
            var result = await _apiClient.PostAsync(new Uri(string.Format(_serviceUrl + "{0}", "/api/classBooks/addStudent")), content);

            if (result.IsSuccessStatusCode)
            {
                var item = await result.Content.ReadAsStringAsync();
                var items = JsonConvert.DeserializeObject<ClassBook>(item);
                return Json(items, JsonRequestBehavior.AllowGet);
            }

            return null;
        }

        public async Task<JsonResult> RemoveStudent(ClassBookBindingModel id)
        {
            var content = new StringContent(JsonConvert.SerializeObject(id), Encoding.UTF8, "application/json");
            var result = await _apiClient.PostAsync(new Uri(string.Format(_serviceUrl + "{0}", "/api/classBooks/removeStudent")), content);

            if (result.IsSuccessStatusCode)
            {
                var item = await result.Content.ReadAsStringAsync();
                var items = JsonConvert.DeserializeObject<ClassBook>(item);
                return Json(items, JsonRequestBehavior.AllowGet);
            }

            return null;
        }
        

    }
}

ClassBooksWebApp/Controllers/PatternsController.cs
using ClassBooksWebApp.Models;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Net;
using System.Net.Http;
using System.Text;
using System.Threading.Tasks;
using System.Web.Configuration;
using System.Web.Mvc;

namespace ClassBooksWebApp.Controllers
{
    public class PatternsController : Controller
    {
        readonly HttpClient _apiClient = new HttpClient();
        private readonly string _serviceUrl = WebConfigurationManager.AppSettings["apiUrl"];

        // GET: Patterns
        public ActionResult Index()
        {
            if (Session["UserId"] == null) return View("~/Views/Login/Login.cshtml");
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> GetPatterns()
        {
            var response = await _apiClient.GetAsync(new Uri(string.Format(_serviceUrl + "/api/{0}/patterns", new Guid(Session["UserId"].ToString().Replace("\"", "")))));

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var items = JsonConvert.DeserializeObject<List<Pattern>>(content);

                foreach (var item in items)
                {
                    item.Image = null;
                }
                return Json(items, JsonRequestBehavior.AllowGet);
            }

            return null;
        }

        [HttpGet]
        public async Task<JsonResult> GetPublishedPatterns()
        {
            var response = await _apiClient.GetAsync(new Uri(_serviceUrl + "/api/patterns/published"));

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var items = JsonConvert.DeserializeObject<List<Pattern>>(content);

                foreach (var item in items)
                {
                    item.Image = null;
                }
                return Json(items, JsonRequestBehavior.AllowGet);
            }

            return null;
        }

        public async Task<HttpStatusCodeResult> Publish(int id)
        {
            var response = await _apiClient.PostAsync(new Uri(string.Format(_serviceUrl + "{0}/{1}", "/api/patterns/publish", id)), null);

            if (response.IsSuccessStatusCode)
            {
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }

        public async Task<JsonResult> GetPatternImage(int id)
        {
            var response = await _apiClient.GetAsync(new Uri(string.Format(_serviceUrl + "/api/patterns/pattern/{0}", id)));

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var item = JsonConvert.DeserializeObject<Pattern>(content);

                using (var ms = new MemoryStream(item.Image))
                {
                    var bmp = new Bitmap(ms);

                    var scaled = new Bitmap(bmp, new Size(578, 839));
                    item.Image = ToByteArray(scaled, ImageFormat.Jpeg);

                    return Json(item, JsonRequestBehavior.AllowGet);
                }
            }

            return null;
        }

        // get answer sheet by pattern id
        [HttpGet]
        public async Task<JsonResult> GetAnswerSheet(int id)
        {
            var response = await _apiClient.GetAsync(new Uri(string.Format(_serviceUrl + "/api/pattern/{0}/answerSheet", id)));

            if (response.IsSuccessStatusCode)
            {
                var content = await response.Content.ReadAsStringAsync();
                var items = JsonConvert.DeserializeObject<List<AnswerSheet>>(content);
                return Json(items, JsonRequestBehavior.AllowGet);
            }

            return null;
        }

        [HttpPost]
        public async Task<HttpStatusCodeResult> AddAnswerSheet(List<AnswerSheet> answerSheet)
        {
            var content = new StringContent(JsonConvert.SerializeObject(answerSheet), Encoding.UTF8, "application/json");
            var response = await _apiClient.PostAsync(new Uri(string.Format(_serviceUrl + "{0}", "/api/patterns/AddSheet")), content);

            if (response.IsSuccessStatusCode)
            {
                return new HttpStatusCodeResult(HttpStatusCode.OK);
            }

            return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        }



        public async Task<HttpStatusCodeResult> AddPattern(Pattern pattern)
        {
            pattern.TeacherId = Session["UserId"].ToString().Replace("\"", "");

            var content = new StringContent(JsonConvert.SerializeObject(pattern), Encoding.UTF8, "application/json");
            var result = await _apiClient.PostAsync(new Uri(string.Format(_serviceUrl + "{0}", "/api/patterns/addPattern")), content);

            return new HttpStatusCodeResult(HttpStatusCode.Created);

        }

        public async Task<HttpStatusCodeResult> RemovePattern(int id)
        {
            await _apiClient.PostAsync(new Uri(string.Format(_serviceUrl + "{0}/{1}", "/api/DeletePattern", id)), null);

            return new HttpStatusCodeResult(HttpStatusCode.OK);
        }

        public byte[] ToByteArray(Image image, ImageFormat format)
        {
            using (MemoryStream ms = new MemoryStream())
            {
                image.Save(ms, format);
                return ms.ToArray();
            }
        }
    }
}

ClassBooksWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @section scripts{
        <script src="~/Scripts/angular.js"></script>
    }

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Login", "Login", "Login")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @RenderSection("scripts", required: false)
</body>
</html>

ClassBooksWebApp/Views/Shared/_LoggedLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @section scripts{
        <script src="~/Scripts/angular.js"></script>
    }

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Class Books", "Index", "ClassBook")</li>
                    <li>@Html.ActionLink("Test Patterns", "Index", "Patterns")</li>
                    <li>@Html.ActionLink("Logout", "Logout", "Login")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @RenderSection("scripts", required: false)
</body>
</html>

ClassBooksWebApp/Views/Shared/_LoggedStudentsLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @section scripts{
        <script src="~/Scripts/angular.js"></script>
    }

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Logout", "Logout", "Login")</li>

                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/angular")
    @RenderSection("scripts", required: false)
</body>
</html>